[package]
name = "test"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["ws"] }
base64 = "0.22.1"
dashmap = "6.1.0"
futures = "0.3.32"
hex = "0.4.3"
pqcrypto-dilithium = "0.5.0"
pqcrypto-traits = "0.3.5"
rand = "0.10.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.11.0"
tokio = { version = "1.52.1", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
